[controller]
file = "state_controller.py"

[sim]
physics = "first_principles"
drone_model = "cf21B_500"
camera_view = [ 5.0, 180.0, -25.0, 0.0, 0.0, 0.0,]
freq = 500
attitude_freq = 500
render = false

[env]
id = "AIGPDroneRacing-v0"
seed = "random"
freq = 50
sensor_range = 100.0
control_mode = "attitude"

[env.track]
randomize = false
obstacles = []
[[env.track.gates]]
pos = [ -3.0, 0.0, 1.0,]
rpy = [ 0.0, 0.0, 0.0,]

[[env.track.gates]]
pos = [ 0.0, 2.5, 1.2,]
rpy = [ 0.0, 0.0, 1.57,]

[[env.track.gates]]
pos = [ 3.0, 0.0, 1.0,]
rpy = [ 0.0, 0.0, 3.14159,]

[[env.track.gates]]
pos = [ 0.0, -2.5, 0.8,]
rpy = [ 0.0, 0.0, -1.57,]

[[env.track.drones]]
pos = [ -5.0, 0.0, 1.0,]
rpy = [ 0.0, 0.0, 0.0,]
vel = [ 0.0, 0.0, 0.0,]
ang_vel = [ 0.0, 0.0, 0.0,]

[env.track.safety_limits]
pos_limit_low = [ -8.0, -5.0, 0.0,]
pos_limit_high = [ 8.0, 5.0, 4.0,]

[env.track.gate_size]
width = 1.52
height = 1.52
tolerance = 0.35
