# Level 1

# | Evaluation Scenario | Rand. Inertial Properties | Randomized Obstacles, Gates | Notes    |
# | :-----------------: | :-----------------------: | :-------------------------: | :------: |
# | `level1.toml`       | **Yes**                   | **No**                     | Adaptive |
[controller]
file = "trajectory_controller.py" # Put your controller file name here. Specifying a controller as argument to scripts will override this setting. Controllers are located in `lsy_drone_racing/control/`

[deploy]
### Settings only relevant for deployment
# Whether to check if gate and obstacle positions observed by vicon are within the limits defined down below.
check_race_track = true
# Whether to check if the drone start position is within the limits specified down below.
check_drone_start_pos = true
# Lets you practice your controller without putting up gates & obstacles, assumes nominal positions given below.
real_track_objects = true

[[deploy.drones]]
id = 91
channel = 100

[sim]
# Physics options: analytical, sys_id, mujoco
physics = "analytical"
camera_view = [5.0, -40.0, -40.0, 0.5, -1.0, 0.5]
freq = 500                                        # Simulation frequency, in Hz
attitude_freq = 500                               # Controller frequency, in Hz. This frequency is used to simulate the onboard controller, NOT for the environment's step function
gui = false                                       # Enable/disable PyBullet's GUI

[env]
id = "DroneRacing-v0"   # "DroneRacing-v0" for single races, "MultiDroneRacing-v0" for multi-drone races. Each environment also implements a vector-environment for faster training
seed = 1337             # Random seed
freq = 50               # Frequency of the environment's step function, in Hz
sensor_range = 0.7      # Range at which the exact location of gates and obstacles become visible to the drone. Objects that are not in the drone's sensor range report their nominal position.
control_mode = "state"  # Control mode of the environment. Can be either "state" or "attitude"

[env.track]
# Tall gates: 1.0m height. Short gates: 0.525m height. Height is measured from the ground to the
# center of the gate.
[[env.track.gates]]
pos = [0.45, -0.5, 0.56]
rpy = [0.0, 0.0, 2.35]
[[env.track.gates]]
pos = [1.0, -1.05, 1.11]
rpy = [0.0, 0.0, -0.78]
[[env.track.gates]]
pos = [0.0, 1.0, 0.56]
rpy = [0.0, 0.0, 0.0]
[[env.track.gates]]
pos = [-0.5, 0.0, 1.11]
rpy = [0.0, 0.0, 3.14]

# Obstacle height: 1.4m. Height is measured from the ground to the top of the obstacle.
[[env.track.obstacles]]
pos = [1.0, 0.0, 1.4]
[[env.track.obstacles]]
pos = [0.5, -1.0, 1.4]
[[env.track.obstacles]]
pos = [0.0, 1.5, 1.4]
[[env.track.obstacles]]
pos = [-0.5, 0.5, 1.4]

[[env.track.drones]]
pos = [1.0, 1.5, 0.07]
rpy = [0, 0, 0]
vel = [0, 0, 0]
ang_vel = [0, 0, 0]

[env.disturbances.action]
fn = "normal"
scale = 0.001

[env.disturbances.dynamics]
fn = "uniform"
[env.disturbances.dynamics.kwargs]
minval = [-0.1, -0.1, -0.1]
maxval = [0.1, 0.1, 0.1]

[env.randomizations.drone_pos]
fn = "uniform"
[env.randomizations.drone_pos.kwargs]
minval = [-0.1, -0.1, 0.0]
maxval = [0.1, 0.1, 0.02]

[env.randomizations.drone_rpy]
fn = "uniform"
[env.randomizations.drone_rpy.kwargs]
minval = [-0.1, -0.1, -0.1]
maxval = [0.1, 0.1, 0.1]

[env.randomizations.drone_mass]
fn = "uniform"
[env.randomizations.drone_mass.kwargs]
minval = -0.01
maxval = 0.01

[env.randomizations.drone_inertia]
fn = "uniform"
[env.randomizations.drone_inertia.kwargs]
minval = [-0.000001, -0.000001, -0.000001]
maxval = [0.000001, 0.000001, 0.000001]
