[ta1]
name = "Martin (TA)"
github = "amacati"
time = 27.08235294117647
success_rate = 0.85
submissions = 1

[ta2]
name = "Marcel (TA)"
github = "ratheron"
time = 20.06125
success_rate = 0.8
submissions = 5

[ta3]
name = "Radu (TA)"
github = "rducrist"
time = 28.290000000000003
success_rate = 0.6
submissions = 1

[ta4]
name = "Yuming (TA)"
github = "Yuming-Lee24"

[team1]
name = "Millennium Falcon"
github = "masfgithub"
time = 5.998333333333332
success_rate = 0.6
submissions = 6

[team2]
name = "Sama & Luc"
github = "sama-abuassad"

[team3]
name = "Thunderstrike"
github = "Qshao007"

[team4]
name = "IshowSpeed"
github = "HongMinhNhat35"

[team5]
name = "Release the drone"
github = "VJandl"

[team6]
name = "aaa"
github = "RuiyangHuang28"

[team7]
name = "Sandro & Marek"
github = "aloisi101-bit"
time = 9.347272727272726
success_rate = 0.55
submissions = 1

[team8]
name = "Okan"
github = "okanarif"

[team9]
name = "Timo & Jeffrey"
github = "mangam-02"
time = 8.661666666666667
success_rate = 0.6
submissions = 14

[team10]
name = "Nikola & Moritz"
github = "SarNi434"
time = 4.8963636363636365
success_rate = 0.55
submissions = 9

[team11]
name = "Theo & Olcay"
github = "olcayakgn"
time = 8.66
success_rate = 0.5
submissions = 4

[team12]
name = "Celia & Paula"
github = "celplasan"

[team13]
name = "Leonie & Nicolas"
github = "leonie0206"

[team14]
name = "Wei Lun & Lars"
github = "ang-weilun"
time = 6.221666666666667
success_rate = 0.6
submissions = 4

[team15]
name = "Xiaochen & Aoji"
github = "stateirving"
time = 9.318181818181817
success_rate = 0.55
submissions = 2

[team16]
name = "Deniz & Ahmet"
github = "denizozturk95"
time = 6.494
success_rate = 0.5
submissions = 10

[team17]
name = "FlyingPacers (MAADR)"
github = "sebastianserna30"
time = 7.690909090909091
success_rate = 0.55
submissions = 1

[team18]
name = "Justin & Finn"
github = "fbesong"

[team19]
name = "XYZ"
github = "NoMoreNameToUse"
time = 9.338461538461537
success_rate = 0.65
submissions = 1

[team20]
name = "Ka-Fa 1500"
github = "deniz-onat"
time = 8.808333333333334
success_rate = 0.6
submissions = 1

[team21]
name = "eagle"
github = "cyuzuzo-j"

[team22]
name = "Philipp (MAADR)"
github = "philippreinig"

[team23]
name = "Moritz (MAADR)"
github = "moritzschueler"
